### ISSUE TITLE
Add instructions to create uf2

### ISSUE THREAD

**Issue by mariogamer2** [euclala/RCM-X86#2]
Are the official instruction ok?

**Comment by mariogamer2** [comment]
https://learn.adafruit.com/adafruit-feather-m0-express-designed-for-circuit-python-circuitpython?view=all

But I don't think they apply, because you need to embbed the payload.

**Comment by clockterra** [comment]
i make a uf2 file doing the conversion on that guide mariogame2, but i found a problem my uf2 files are not the same size as the euclala...

BIN files: / UF2 converted:
Hekate3.2 bin = 124 kb / hekate 3.2 = 247 kb
Reinx new = 69 kb / Reinx new = 137 kb
SXOS 1.0 = 28 kb / SXOS 1.0 = 55 kb
euclala original files, 
HBL32.uf2 = 275 kb
TXOS.uf2 = 85 kb

maybe something is wrong...
Please euclala could you convert the REINX payload, for me is the most important..(you have done all others).

**Comment by mariogamer2** [comment]
That's mot how you are supposed to do you need a bootloader to run on the actjal trinket and a payload to add intk this bootloader.

**Comment by clockterra** [comment]
i know now, i have done it with build (arduino ide) and putting my converted payloads (.bin to .h) there and it works nice...
Then take the arduine compiled .bin or .hex and convert it to uf2 file and it's perfect match (works all payloads)...
except the TXOS (TXOS.h = 146kb) that euclala one's is diferent size that the ones from Team Xecuter (the one that i converted is SXOX.h = 168 kb

Maybe euclala used source to modify TXOS payload as he want??.

**Comment by nicoboss** [comment]
@clockterra Can you please link that EOL forum thread you mentioned?

**Comment by mariogamer2** [comment]
Could you translate it?

**Comment by mariogamer2** [comment]
The issue is actually fixed. A link was included in the readme.
