### ISSUE TITLE
After load UF2 RCM-X86 v2 stop works.

### ISSUE THREAD

**Issue by Icedtouch** [euclala/RCM-X86#3]
I followed the guide to start using the device but I was not recognized by the CPU at the time of pressing the RES twice. Then I followed the guide of the FIX has started to work properly but when loading the UF2 according to the guide has stopped working. I try again to load the FIX but the CPU does not recognize me. What solution could I apply?

**Comment by euclala** [comment]
try to do this https://github.com/euclala/fix_dongle/blob/master/hardware_fix.jpg
